# Copyright 2018 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a Apache
# license that can be found in the LICENSE file.

language: go

go:
- '1.11'
- 'tip'

go_import_path: github.com/chai2010/libconfd

script:
- env GO111MODULE=on go test github.com/chai2010/libconfd/...
- env GO111MODULE=on go vet github.com/chai2010/libconfd/...

- env GO111MODULE=on go test github.com/chai2010/libconfd/etcdv3/...
- env GO111MODULE=on go vet github.com/chai2010/libconfd/etcdv3/...
